In [ ]:
'''1. Create a class Employee and then do the following
• Create a data member to count the number of Employees
• Create a constructor to initialize name, family, salary, department
• Create a function to average salary
• Create a Fulltime Employee class and it should inherit the properties of Employee class
• Create the instances of Fulltime Employee class and Employee class and call their member functions.'''

In [4]:
class Employee:
    employee_count = 0
    benefits = None
    def __init__(self,name,family,salary,department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count+=1

    def avg_salary(employees):
        total_salary = sum(emp.salary for emp in employees)
        return total_salary/len(employees)

class Fulltime_Employee(Employee):
    def __init__(self, name, family, salary, department, benefits):
        super().__init__(name, family, salary, department)
        self.benefits = benefits


if __name__=='__main__':
    emp1 = Employee('Rakesh','Kanmani',15000,'IT')
    emp2 = Employee('Jhansi','Teji',35000,'Pharmaceuticals')
    emp3 = Fulltime_Employee('Rishi','Smiley',50000,'Finance',True)

    employees = [emp1,emp2,emp3]
    print("Employee Details: ")
    for emp in employees:
        print(emp.name,emp.family, emp.salary, emp.department, emp.benefits)

    print("\nTotal Employees:", Employee.employee_count)
    print("Average Salary:", Employee.avg_salary(employees))

Employee Details: 
Rakesh Kanmani 15000 IT None
Jhansi Teji 35000 Pharmaceuticals None
Rishi Smiley 50000 Finance True

Total Employees: 3
Average Salary: 33333.333333333336


In [ ]:
'''2. Numpy
Using NumPy create random vector of size 20 having only float in the range 1-20.
Then reshape the array to 4 by 5
Then replace the max in each row by 0 (axis=1)
(you can NOT implement it via for loop)'''

In [5]:
import numpy as np
# Creating a vector of size '20'of float values with range between 1 to 20
random_vector = np.random.uniform(1,20,20)
# Shaping the array using reshape() function to 4 by 5 matrix
reshaped_array = random_vector.copy().reshape(4,5)
# Getting the indices of maximum value in each row
max_indices = reshaped_array.argmax(axis=1)
# Making the max values in each row to zero
reshaped_array[np.arange(reshaped_array.shape[0]),max_indices] = 0

print("Original Vector Array: \n")
print(random_vector)
print("\nReshaped Array with 0 replacing the max in each row: \n")
print(reshaped_array)

Original Vector Array: 

[ 5.35308606  9.36605167  4.50163387 17.6294162   3.26348217 18.64596124
  2.3482206   2.63693438  7.99687591  2.699411   15.6968606   4.06386514
 19.89903844  6.69761357  7.36584444 15.05599152 15.10131841 17.82056695
 11.08559262 11.06650929]

Reshaped Array with 0 replacing the max in each row: 

[[ 5.35308606  9.36605167  4.50163387  0.          3.26348217]
 [ 0.          2.3482206   2.63693438  7.99687591  2.699411  ]
 [15.6968606   4.06386514  0.          6.69761357  7.36584444]
 [15.05599152 15.10131841  0.         11.08559262 11.06650929]]
